eureka:
  instance:
    hostname: localhost
    instanceId: localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: hello
